### ISSUE TITLE
Resolve problems with Layout (backend/bootstrap)

### ISSUE THREAD

**Issue by watashiwalds** [DungZan/BTL_LTWeb#48]
- [ ] Caurosel của sản phẩm (sửa khoảng trống lớn giữa các thẻ trong các hàng?)
- [x] Xếp sản phẩm theo Tên, Giá
- [ ] Lọc sản phẩm theo kích thước, màu
- [x] Link đến các bộ sưu tập (Nữ, Trẻ, Nam) (Xoá nếu không cần thiết)
- [ ] Sửa tình trạng không hiển thị ảnh của caurosel Bộ sưu tập khi mở trang trên điện thoại (F12)
- [ ] Sửa hiển thị footer khi mở header menu trên điện thoại (footer nhảy bật lên đầu trang khi mở menu)

**Comment by Mr-1504** [comment]
> Chặn mie điện thoại không cho vào :(((( Pực

gà:))

**Comment by Mr-1504** [comment]
> * [ ]  Caurosel của sản phẩm (sửa khoảng trống lớn giữa các thẻ trong các hàng?)
> * [x]  Xếp sản phẩm theo Tên, Giá
> * [ ]  Lọc sản phẩm theo kích thước, màu
> * [x]  Link đến các bộ sưu tập (Nữ, Trẻ, Nam) (Xoá nếu không cần thiết)
> * [ ]  Sửa tình trạng không hiển thị ảnh của caurosel Bộ sưu tập khi mở trang trên điện thoại (F12)
> * [ ]  Sửa hiển thị footer khi mở header menu trên điện thoại (footer nhảy bật lên đầu trang khi mở menu)

Giỏi quá:))
